### ISSUE TITLE
Exercise 6 Task 3: Cosmos DB trigger function Error

### ISSUE THREAD

**Issue by snpdev** [Microsoft/MCW-OSS-PaaS-and-DevOps#19] opened 2019-03-25 16:01 UTC
In Exercise 6, Task 3 - Upon creating the Cosmos DB trigger function, the following message is displayed:

> Error: Failed to start language worker process for: node.

![image](https://user-images.githubusercontent.com/1825479/54934413-d855d000-4ef4-11e9-968d-f1df063b1a2f.png)

To resolve the problem I followed the instructions at https://github.com/MicrosoftDocs/azure-docs/issues/17295, namely to change the  Application Settings,  WEBSITE_NODE_DEFAULT_VALUE value from 10.14.1 to 8.11.1.

I recommend that a note be added to the step by step instructions.

**Comment by DawnmarieDesJardins** [comment] 2019-03-25 18:55
@kylebunting 
Thanks Mike!  This workshop is currently undergoing an update.  Assigning this issue to author for review.

**Comment by kylebunting** [comment] 2019-04-07 19:58
@snpdev, I was unable to reproduce this issue while testing and doing the latest update. The issue you referenced in the docs appears to have been resolved, so maybe this is no longer an issue?

I'll continue to monitor, and if the issue appears, I'll add a note into the lab about steps to mitigate based on your instructions above.

**Comment by A142838** [comment] 2019-04-16 13:45
@kylebunting I have the issue for even after setting node version 8.11.1 please let me know any details you might need to get this issue resolved

**Comment by kylebunting** [comment] 2019-04-18 20:08
@A142838, I have still not been able to reproduce this issue. Could you check to see what the runtime version of your function app is on the Function app settings page? Also, could you try deleting your function app and recreating it to see if the error goes away? I have now run through this several times, and I don't get any errors creating the functions.

**Comment by kylebunting** [comment] 2019-04-18 20:15
@A142838, correction to the above. Just after I posted the comment, I got the error. Updating the node version to 8.11.1 worked for me, but I'll dig in further to see if I can do anything to get rid of the error. I'll also add a note in the steps on how to update the node settings, should anyone else get the error.

**Comment by A142838** [comment] 2019-04-19 03:43
@kylebunting Thanks for help in replicating the issue I have the issue even after setting the node version to 8.11.1 but the issue but once I restart after deployment in my CD pipeline it is fine. Also, the other thing is in the process explorer the node language worked process does show up but looks like it crashed soon after and the function app then just keeps returning 500.

**Comment by kylebunting** [comment] 2019-04-22 13:29
I've added a note into the workshop HOL on how to address the issue. This appears to be a bug with the node language worker process, so I'm closing for now, but will continue to monitor and add in corrections as the issue is addressed.

**Closed by kylebunting** 2019-04-22 13:29 UTC
